#!/bin/bash

sudo docker run -d cloudflare/cloudflared:latest tunnel --no-autoupdate run --token eyJhIjoiMzA2NjQ2NDExOGZmMTA1MjJmNTZkZTVmYTViYzIxZTciLCJ0IjoiMjgzMDI5NmUtY2ZmYy00YjVlLThhNjgtMGQzZjllMzQ5NzAzIiwicyI6Ik9XTTVZbVV6TW1FdFpXUm1NeTAwWWpSaUxUbGpaVFF0TmpBeU5XTTRNVEptTXpWaSJ9
